import Head from 'next/head'
import Image from 'next/image'
import HeroBackground from '../../public/hero_background.jpg'
import HeroCTA from './components/heroCTA'
import Testimonials from './components/testimonial'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Image src={HeroBackground} alt="Pine wood panels background" className='w-full h-[434px] object-cover absolute inset-0 -z-10' />
        <HeroCTA />
        {/* Testimonials */}
        <div className='px-4 py-8 bg-amber-200'>
          <Testimonials />
        </div>
      </main>
    </>
  )
}
